// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic.proto

package com.xy.grpc.core.generic;

public final class GenericProto {
  private GenericProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generic_GenericRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generic_GenericRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generic_GenericRequest_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generic_GenericRequest_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generic_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generic_GenericResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generic_GenericResponse_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generic_GenericResponse_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgeneric.proto\022\007generic\"\230\001\n\016GenericRequ" +
      "est\022\013\n\003url\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014\0227\n\010met" +
      "adata\030\003 \003(\0132%.generic.GenericRequest.Met" +
      "adataEntry\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\"\254\001\n\017GenericResponse\022" +
      "\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\017\n\007payloa" +
      "d\030\003 \001(\014\0228\n\010metadata\030\004 \003(\0132&.generic.Gene" +
      "ricResponse.MetadataEntry\032/\n\rMetadataEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012K\n\016Ge" +
      "nericService\0229\n\004Call\022\027.generic.GenericRe" +
      "quest\032\030.generic.GenericResponseB*\n\030com.x" +
      "y.grpc.core.genericB\014GenericProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_generic_GenericRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_generic_GenericRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generic_GenericRequest_descriptor,
        new java.lang.String[] { "Url", "Payload", "Metadata", });
    internal_static_generic_GenericRequest_MetadataEntry_descriptor =
      internal_static_generic_GenericRequest_descriptor.getNestedTypes().get(0);
    internal_static_generic_GenericRequest_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generic_GenericRequest_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_generic_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_generic_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generic_GenericResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Payload", "Metadata", });
    internal_static_generic_GenericResponse_MetadataEntry_descriptor =
      internal_static_generic_GenericResponse_descriptor.getNestedTypes().get(0);
    internal_static_generic_GenericResponse_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generic_GenericResponse_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
